# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.open-in-view=false
spring.sql.init.mode=always


# LOGS
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always


# PAGINATION
spring.data.web.pageable.default-page-size=15
spring.data.web.pageable.max-page-size=100


# CAS
cas.server-url=${CAS_SERVER_URL}
cas.service-url=${BACKEND_URL}/cas/callback


# JWT
app.secret-key=${JWT_SECRET}
app.expiration-time=900000
app.refresh-expiration=604800000


# FRONTEND
app.frontend-url=${FRONTEND_URL}

# BACKEND
app.backend-url=${BACKEND_URL}


# MAIL
app.mail.from=no-reply@odm.fr
app.mail.from-name=ODM System
app.mail.enabled=true

app.upload.dir=/app/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com